/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const closeToast: typeof import('vant/es')['closeToast']
  const showLoadingToast: typeof import('vant/es')['showLoadingToast']
  const showToast: typeof import('vant/es')['showToast']
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {

  }
}